name: Daily -40 Drop Screen

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 2-6'

jobs:
  run-screen:
    runs-on: ubuntu-latest
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      DATA_API_KEY: ${{ secrets.DATA_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare run directory
        run: mkdir -p runs
      - name: Run screen
        run: |
          python main.py --run
      - name: Upload run log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: runs
